const skills = {
  commonlore: { name: "Common Lore", skillID: "commonlore", gifts: [] },
  naturelore: { name: "Nature Lore", skillID: "naturelore", gifts: [] },
  alchemylore: { name: "Alchemy Lore", skillID: "alchemylore", gifts: [] },
  agility: {
    name: "Agility",
    skillID: "agility",
    gifts: [
      { giftID: "desperation", level: 5 },
      { giftID: "fullunitdodge", level: 5 },
      { giftID: "advantage", level: 10 },
      { giftID: "leap", level: 10 },
      { giftID: "efficient", level: 15 },
      { giftID: "formtofiti", level: 15 },
      { giftID: "twitch", level: 20 },
      { giftID: "attunedinertia", level: 20 },
      { giftID: "massiveevasion", level: 25 },
      { giftID: "rushiii", level: 30 },
      { giftID: "vaulting", level: 35 },
      { giftID: "spunk", level: 40 },
      { giftID: "beat", level: 45 },
      { giftID: "hypertwist", level: 45 },
    ],
  },
  armmuscle: {
    name: "Arm Muscle",
    skillID: "armmuscle",
    gifts: [
      { giftID: "desperation", level: 5 },
      { giftID: "subtlestrength", level: 15 },
      { giftID: "evenkeeled", level: 30 },
      { giftID: "ambidexterity", level: 40 },
      { giftID: "wiry", level: 10 },
      { giftID: "fullkineticblow", level: 35 },
      { giftID: "mightypull", level: 5 },
      { giftID: "burlyandsurly", level: 15 },
      { giftID: "brawn", level: 20 },
      { giftID: "gainedmass", level: 20 },
      { giftID: "mightmakesright", level: 25 },
      { giftID: "formtofitiii", level: 35 },
      { giftID: "shredded", level: 40 },
    ],
  },
  balance: {
    name: "Balance",
    skillID: "balance",
    gifts: [
      { giftID: "fullunitdodge", level: 5 },
      { giftID: "formtofitii", level: 25 },
      { giftID: "rebound", level: 5 },
      { giftID: "braced", level: 10 },
      { giftID: "cautious", level: 10 },
      { giftID: "prevention", level: 10 },
      { giftID: "solid", level: 10 },
      { giftID: "carefulaim", level: 15 },
      { giftID: "gripattack", level: 15 },
      { giftID: "subtlestrength", level: 15 },
      { giftID: "delicatestance", level: 20 },
      { giftID: "lag", level: 20 },
      { giftID: "poised", level: 20 },
      { giftID: "flexibilityi", level: 20 },
      { giftID: "momentum", level: 25 },
      { giftID: "evenkeeled", level: 30 },
      { giftID: "flexibilityii", level: 30 },
      { giftID: "centered", level: 35 },
      { giftID: "prohibition", level: 35 },
      { giftID: "steady", level: 40 },
      { giftID: "unstoppable", level: 45 },
    ],
  },
  awareness: {
    name: "Awareness",
    skillID: "awareness",
    gifts: [
      { giftID: "advantage", level: 10 },
      { giftID: "scan", level: 5 },
      { giftID: "weaken", level: 5 },
      { giftID: "alert", level: 10 },
      { giftID: "understanding", level: 10 },
      { giftID: "lightningsnatch", level: 15 },
      { giftID: "inspect", level: 20 },
      { giftID: "visionary", level: 20 },
      { giftID: "formtofitii", level: 25 },
      { giftID: "wisdom", level: 25 },
      { giftID: "innersight", level: 30 },
      { giftID: "keenaim", level: 35 },
      { giftID: "omniscience", level: 40 },
      { giftID: "harmony", level: 45 },
    ],
  },
  dexterity: {
    name: "Dexterity",
    skillID: "dexterity",
    gifts: [
      { giftID: "efficient", level: 15 },
      { giftID: "formtofiti", level: 15 },
      { giftID: "beat", level: 45 },
      { giftID: "lightningsnatch", level: 15 },
      { giftID: "delicatestance", level: 20 },
      { giftID: "dismantle", level: 15 },
      { giftID: "quickdraw", level: 5 },
      { giftID: "offhandaction", level: 5 },
      { giftID: "penmanship", level: 10 },
      { giftID: "penmanship", level: 10 },
      { giftID: "safeguard", level: 15 },
      { giftID: "vibration", level: 15 },
      { giftID: "flurry", level: 20 },
      { giftID: "lithe", level: 20 },
      { giftID: "contort", level: 20 },
      { giftID: "nimble", level: 20 },
      { giftID: "surgical", level: 25 },
      { giftID: "interrupt", level: 25 },
      { giftID: "careful", level: 25 },
      { giftID: "accurate", level: 30 },
      { giftID: "pierce", level: 35 },
      { giftID: "precise", level: 35 },
      { giftID: "ambidexterity", level: 40 },
      { giftID: "ambush", level: 10 },
    ],
  },
  tactics: {
    name: "Tactics",
    skillID: "tactics",
    gifts: [
      { giftID: "attunedinertia", level: 20 },
      { giftID: "scan", level: 5 },
      { giftID: "inspect", level: 20 },
      { giftID: "prohibition", level: 35 },
      { giftID: "hold", level: 10 },
      { giftID: "deathwish", level: 20 },
      { giftID: "interrupt", level: 25 },
      { giftID: "cadence", level: 10 },
      { giftID: "containi", level: 20 },
      { giftID: "secondwindi", level: 10 },
      { giftID: "preserve", level: 15 },
      { giftID: "strategization", level: 35 },
      { giftID: "unleashed", level: 45 },
      { giftID: "charge", level: 5 },
      { giftID: "exploitweakness", level: 40 },
      { giftID: "perfecttension", level: 5 },
      { giftID: "confront", level: 5 },
      { giftID: "observant", level: 10 },
      { giftID: "calculated", level: 15 },
      { giftID: "goodtiming", level: 15 },
      { giftID: "exacting", level: 30 },
      { giftID: "insightful", level: 30 },
      { giftID: "firststrike", level: 35 },
      { giftID: "intuition", level: 40 },
    ],
  },
  legmuscle: {
    name: "Leg Muscle",
    skillID: "legmuscle",
    gifts: [
      { giftID: "rushiii", level: 30 },
      { giftID: "vaulting", level: 35 },
      { giftID: "intensifyi", level: 10 },
      { giftID: "fullkineticblow", level: 35 },
      { giftID: "charge", level: 5 },
      { giftID: "charge", level: 5 },
      { giftID: "charge", level: 10 },
      { giftID: "coresynergistics", level: 10 },
      { giftID: "rushi", level: 10 },
      { giftID: "flee", level: 15 },
      { giftID: "forerunner", level: 20 },
      { giftID: "plyometrics", level: 20 },
      { giftID: "unburdened", level: 20 },
      { giftID: "rushii", level: 20 },
      { giftID: "lightstep", level: 25 },
      { giftID: "increasedmass", level: 30 },
      { giftID: "enduranceii", level: 35 },
      { giftID: "rushiv", level: 40 },
      { giftID: "dash", level: 45 },
      { giftID: "perfecttension", level: 5 },
    ],
  },
  stealth: {
    name: "Stealth",
    skillID: "stealth",
    gifts: [
      { giftID: "hypertwist", level: 45 },
      { giftID: "penmanship", level: 10 },
      { giftID: "mortalcombatant", level: 25 },
      { giftID: "conceal", level: 20 },
      { giftID: "richochet", level: 35 },
      { giftID: "flee", level: 15 },
      { giftID: "ambush", level: 5 },
      { giftID: "ambush", level: 10 },
      { giftID: "subtlety", level: 10 },
      { giftID: "unseenmove", level: 20 },
      { giftID: "mystique", level: 25 },
      { giftID: "assassinate", level: 30 },
      { giftID: "juke", level: 30 },
      { giftID: "unremarkable", level: 35 },
      { giftID: "exploitweakness", level: 40 },
      { giftID: "perfecttension", level: 45 },
    ],
  },
  authority: {
    name: "Authority",
    skillID: "authority",
    gifts: [
      { giftID: "demoralize", level: 5 },
      { giftID: "rallycry", level: 10 },
      { giftID: "aggression", level: 15 },
      { giftID: "impactii", level: 15 },
      { giftID: "largerthanlife", level: 20 },
      { giftID: "resolve", level: 20 },
      { giftID: "confidence", level: 25 },
      { giftID: "valorous", level: 30 },
      { giftID: "responsibility", level: 35 },
      { giftID: "gloriouspresence", level: 40 },
    ],
  },
  courage: {
    name: "Courage",
    skillID: "courage",
    gifts: [
      { giftID: "rallycry", level: 10 },
      { giftID: "largerthanlife", level: 20 },
      { giftID: "encourage", level: 5 },
      { giftID: "hold", level: 10 },
      { giftID: "intensifyi", level: 10 },
      { giftID: "intensifyi", level: 10 },
      { giftID: "overcoming", level: 15 },
      { giftID: "deathwish", level: 20 },
      { giftID: "fortitudei", level: 20 },
      { giftID: "indomitablecharacter", level: 25 },
      { giftID: "heroism", level: 25 },
      { giftID: "fortitudeii", level: 25 },
      { giftID: "grit", level: 30 },
      { giftID: "fortitudeiii", level: 30 },
      { giftID: "heart", level: 35 },
      { giftID: "fortitudeiv", level: 35 },
      { giftID: "fortitudev", level: 40 },
      { giftID: "vulnerability", level: 45 },
      { giftID: "charge", level: 10 },
    ],
  },
  inscription: {
    name: "Inscription",
    skillID: "inscription",
    gifts: [
      { giftID: "impactii", level: 15 },
      { giftID: "weaken", level: 5 },
      { giftID: "intensifyi", level: 10 },
      { giftID: "combineii", level: 30 },
      { giftID: "directi", level: 5 },
      { giftID: "durationi", level: 5 },
      { giftID: "impacti", level: 5 },
      { giftID: "magnifyi", level: 5 },
      { giftID: "rangei", level: 5 },
      { giftID: "bounce", level: 10 },
      { giftID: "trigger:touch", level: 10 },
      { giftID: "rangeii", level: 10 },
      { giftID: "cone", level: 15 },
      { giftID: "directii", level: 15 },
      { giftID: "combinei", level: 15 },
      { giftID: "durationii", level: 15 },
      { giftID: "enchant:charge", level: 15 },
      { giftID: "enchant:infinity", level: 15 },
      { giftID: "conceal", level: 20 },
      { giftID: "containi", level: 20 },
      { giftID: "devastation", level: 20 },
      { giftID: "radius", level: 20 },
      { giftID: "reverse", level: 20 },
      { giftID: "ruminate", level: 20 },
      { giftID: "directiii", level: 25 },
      { giftID: "impactiii", level: 25 },
      { giftID: "magnifyii", level: 25 },
      { giftID: "rangeiii", level: 25 },
      { giftID: "intensifyii", level: 30 },
      { giftID: "trigger:sense", level: 30 },
      { giftID: "attuned", level: 30 },
      { giftID: "containii", level: 30 },
      { giftID: "durationiii", level: 35 },
      { giftID: "quicken", level: 35 },
      { giftID: "enchant:recharge", level: 35 },
      { giftID: "impactiv", level: 35 },
      { giftID: "ascendance", level: 40 },
      { giftID: "combineiii", level: 40 },
      { giftID: "magnifyiii", level: 40 },
      { giftID: "trigger:action", level: 40 },
      { giftID: "burst", level: 45 },
      { giftID: "formcontrol", level: 45 },
      { giftID: "impactv", level: 45 },
      { giftID: "permanence", level: 45 },
    ],
  },
  toughness: {
    name: "Toughness",
    skillID: "toughness",
    gifts: [
      { giftID: "largerthanlife", level: 20 },
      { giftID: "fend", level: 25 },
      { giftID: "preserve", level: 15 },
      { giftID: "secondwindiii", level: 40 },
      { giftID: "ruthlessnessi", level: 5 },
      { giftID: "stoici", level: 10 },
      { giftID: "coarseskin", level: 10 },
      { giftID: "ruthlessnessii", level: 15 },
      { giftID: "stoicii", level: 20 },
      { giftID: "unceasing", level: 20 },
      { giftID: "endurancei", level: 25 },
      { giftID: "roughskin", level: 25 },
      { giftID: "ruthlessnessiii", level: 25 },
      { giftID: "stoiciii", level: 30 },
      { giftID: "ruthlessnessiv", level: 35 },
      { giftID: "starkskin", level: 35 },
      { giftID: "stoiciv", level: 40 },
      { giftID: "immovable", level: 45 },
    ],
  },
  willpower: {
    name: "Willpower",
    skillID: "willpower",
    gifts: [
      { giftID: "largerthanlife", level: 20 },
      { giftID: "resolution", level: 45 },
      { giftID: "durationii", level: 15 },
      { giftID: "secondwindii", level: 25 },
      { giftID: "enduranceii", level: 35 },
      { giftID: "goodtiming", level: 15 },
      { giftID: "ruthlessnessi", level: 5 },
      { giftID: "ruthlessnessii", level: 15 },
      { giftID: "endurancei", level: 25 },
      { giftID: "ruthlessnessiii", level: 25 },
      { giftID: "ruthlessnessiv", level: 35 },
      { giftID: "confident", level: 10 },
      { giftID: "moxie", level: 15 },
      { giftID: "belligerence", level: 20 },
      { giftID: "focused", level: 20 },
      { giftID: "temperance", level: 25 },
      { giftID: "rugged", level: 30 },
      { giftID: "determined", level: 30 },
      { giftID: "intensity", level: 40 },
    ],
  },
  charisma: {
    name: "Charisma",
    skillID: "charisma",
    gifts: [
      { giftID: "gloriouspresence", level: 40 },
      { giftID: "encourage", level: 5 },
      { giftID: "hype", level: 10 },
      { giftID: "inspire", level: 15 },
      { giftID: "agreeable", level: 20 },
      { giftID: "ridicule", level: 20 },
      { giftID: "wordsmith", level: 20 },
      { giftID: "gentle", level: 25 },
      { giftID: "impressiveego", level: 25 },
      { giftID: "savant", level: 30 },
      { giftID: "optimistic", level: 30 },
      { giftID: "humble", level: 35 },
      { giftID: "zeal", level: 45 },
    ],
  },
  handtohand: {
    name: "Hand to Hand",
    skillID: "handtohand",
    gifts: [
      { giftID: "lightningsnatch", level: 15 },
      { giftID: "gripattack", level: 15 },
      { giftID: "unstoppable", level: 45 },
      { giftID: "addkick", level: 5 },
      { giftID: "forcedaim", level: 5 },
      { giftID: "cadence", level: 10 },
      { giftID: "fury", level: 10 },
      { giftID: "wiry", level: 10 },
      { giftID: "palmforce", level: 15 },
      { giftID: "registeredweapons", level: 20 },
      { giftID: "brutalbalance", level: 20 },
      { giftID: "gird", level: 20 },
      { giftID: "spur", level: 20 },
      { giftID: "fend", level: 25 },
      { giftID: "mortalcombatant", level: 25 },
      { giftID: "lethalartist", level: 30 },
      { giftID: "rhythm", level: 30 },
      { giftID: "fullkineticblow", level: 35 },
      { giftID: "untouchable", level: 40 },
    ],
  },
  meditationrest: {
    name: "Meditation/Rest",
    skillID: "meditationrest",
    gifts: [
      { giftID: "innersight", level: 30 },
      { giftID: "durationi", level: 5 },
      { giftID: "containii", level: 30 },
      { giftID: "prepare", level: 5 },
      { giftID: "conviction", level: 10 },
      { giftID: "serenityi", level: 10 },
      { giftID: "secondwindi", level: 10 },
      { giftID: "trusti", level: 10 },
      { giftID: "preserve", level: 15 },
      { giftID: "serenityii", level: 15 },
      { giftID: "strength", level: 15 },
      { giftID: "stillness", level: 15 },
      { giftID: "selfless", level: 20 },
      { giftID: "absolution", level: 20 },
      { giftID: "serenityiii", level: 20 },
      { giftID: "trustii", level: 20 },
      { giftID: "fast", level: 20 },
      { giftID: "secondwindii", level: 25 },
      { giftID: "engaged", level: 25 },
      { giftID: "serenityiv", level: 25 },
      { giftID: "faithful", level: 30 },
      { giftID: "knowledge", level: 30 },
      { giftID: "serenityv", level: 30 },
      { giftID: "trustiii", level: 30 },
      { giftID: "theflow", level: 35 },
      { giftID: "prophecy", level: 35 },
      { giftID: "strategization", level: 35 },
      { giftID: "tranquility", level: 35 },
      { giftID: "trustiv", level: 35 },
      { giftID: "secondwindiii", level: 40 },
      { giftID: "connectedness", level: 40 },
      { giftID: "unleashed", level: 45 },
    ],
  },
  missilethrown: {
    name: "Missile/Thrown",
    skillID: "missilethrown",
    gifts: [
      { giftID: "carefulaim", level: 15 },
      { giftID: "lag", level: 20 },
      { giftID: "flurry", level: 20 },
      { giftID: "rangeii", level: 10 },
      { giftID: "mightypull", level: 5 },
      { giftID: "quickshot", level: 5 },
      { giftID: "doubleshot", level: 10 },
      { giftID: "deadlylucky", level: 20 },
      { giftID: "rapidshot", level: 25 },
      { giftID: "mightyfling", level: 25 },
      { giftID: "tripleshot", level: 30 },
      { giftID: "perfectaim", level: 35 },
      { giftID: "richochet", level: 35 },
      { giftID: "snipeshot", level: 40 },
    ],
  },
  weapons: {
    name: "Weapons",
    skillID: "weapons",
    gifts: [
      { giftID: "momentum", level: 25 },
      { giftID: "pierce", level: 35 },
      { giftID: "brawn", level: 20 },
      { giftID: "finesse", level: 5 },
      { giftID: "lightstrike", level: 5 },
      { giftID: "abuse", level: 10 },
      { giftID: "counter", level: 15 },
      { giftID: "disarmingstrike", level: 20 },
      { giftID: "sinister", level: 20 },
      { giftID: "junkyardfighting", level: 25 },
      { giftID: "riposte", level: 30 },
      { giftID: "masteroffinesse", level: 40 },
      { giftID: "unlimitedability", level: 45 },
      { giftID: "power", level: 5 },
      { giftID: "crush", level: 5 },
      { giftID: "murder", level: 10 },
      { giftID: "bruteforce", level: 15 },
      { giftID: "cleave", level: 20 },
      { giftID: "recklessswings", level: 30 },
      { giftID: "eviscerate", level: 35 },
      { giftID: "masterofpower", level: 40 },
    ],
  },
  craftiness: {
    name: "Craftiness",
    skillID: "craftiness",
    gifts: [
      { giftID: "hardwroughti", level: 5 },
      { giftID: "novicei", level: 5 },
      { giftID: "hobbyist", level: 10 },
      { giftID: "noviceii", level: 10 },
      { giftID: "smallcraft", level: 10 },
      { giftID: "dismantle", level: 15 },
      { giftID: "enhance", level: 15 },
      { giftID: "materialism", level: 15 },
      { giftID: "noviceiii", level: 15 },
      { giftID: "cleverness", level: 20 },
      { giftID: "different", level: 20 },
      { giftID: "enthusiast", level: 20 },
      { giftID: "intermediatei", level: 20 },
      { giftID: "improvise", level: 20 },
      { giftID: "hardwroughtii", level: 25 },
      { giftID: "intermediateii", level: 25 },
      { giftID: "particularcare", level: 25 },
      { giftID: "combineii", level: 30 },
      { giftID: "devotee", level: 30 },
      { giftID: "discoveredtalent", level: 30 },
      { giftID: "intermediateiii", level: 30 },
      { giftID: "quirky", level: 30 },
      { giftID: "experti", level: 35 },
      { giftID: "hardwroughtiii", level: 35 },
      { giftID: "mindcraft", level: 35 },
      { giftID: "eccentric", level: 40 },
      { giftID: "elevate", level: 40 },
      { giftID: "expertii", level: 40 },
      { giftID: "master", level: 45 },
      { giftID: "resolution", level: 45 },
    ],
  },
  secondaryart: {
    name: "Secondary Art",
    skillID: "secondaryart",
    gifts: [
      { giftID: "hobbyist", level: 10 },
      { giftID: "enthusiast", level: 20 },
      { giftID: "devotee", level: 30 },
    ],
  },
  oneloreartofchoice: {
    name: "One Lore Art of Choice",
    skillID: "oneloreartofchoice",
    gifts: [{ giftID: "devastation", level: 20 }],
  },
  essencelore: {
    name: "Essence Lore",
    skillID: "essencelore",
    gifts: [
      { giftID: "combineiii", level: 40 },
      { giftID: "permanence", level: 45 },
    ],
  },
};
